GET /api/v1/companies/ad084d60-04d6-41c6-a157-f7ebceeeae3c
Host: localhost:19966
Accept: application/json

###
GET /api/v1/projects/ad084d60-04d6-41c6-a157-f7ebceeeae3c
Host: localhost:19966
Accept: application/json

###
GET /api/v1/contractors/ad084d60-04d6-41c6-a157-f7ebceeeae3c
Host: localhost:19966
Accept: application/json