GET /healthz/ready
Host: localhost:19966
Accept: application/json

###
GET /books
Host: localhost:19966
Accept: application/json

###
GET /books/671238
Host: localhost:19966
Accept: application/json

###
POST /books
Host: localhost:19966
Content-Type: application/json

{
  "id": 464095,
  "title": "Java Concurrency на практике",
  "author": "Гетц",
  "yearOfPublishing": "2020-01-01",
  "genre": "Программирование",
  "pages": 464,
  "hasEpubVersion": true
}

###
PUT /books/464095
Host: localhost:19966
Content-Type: application/json

{
  "id": 464095,
  "title": "Java Concurrency на практике",
  "author": "Гетц",
  "yearOfPublishing": "2020-01-01",
  "genre": "Программирование",
  "pages": 500,
  "hasEpubVersion": true
}

###
DELETE /books/695676
Host: localhost:19966